/* Generated by _build/sync_shop.py from the Weebly store. Do not edit by hand: change the store,
   or EXCLUDE / GROUPS in the script. */
window.SHOP = {
  "synced": "2026-09-28T23:51Z",
  "store": "https://shop.thepaintedladynapavalley.com",
  "groups": [
    "Memberships & gifts",
    "Spray tans",
    "UV tanning",
    "Wellness",
    "Take-home",
    "More deals"
  ],
  "items": [
  {
    "id": 85,
    "group": "Memberships & gifts",
    "name": "$200 Gift Certificate for $100",
    "price": 100.0,
    "was": 200.0,
    "desc": "🎁✨ HOLIDAY GIFT CERTIFICATE SPECIAL ✨🎁 💝 Give $200 — Pay $100! 💝 Now through 🎄 Christmas , enjoy this limited-time gift certificate special at 💕 The Painted Lady . Purchase a $200 gift certificate for just $100 — perfect for gifting 🎁 or treating yourself 💅✨ (highly encouraged). When purchasing, just let us know: 🎀 Who it’s for 💌 Who it’s from 📬 Whether you’d like to pick it up or have us mail it 🎄 Available now through Christmas 💖 Quantities may be limited",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p85_i1_w1432.jpeg?width=640",
    "url": "https://shop.thepaintedladynapavalley.com/store/p85/%24200_Gift_Certificate_for_%24100.html"
  },
  {
    "id": 81,
    "group": "Memberships & gifts",
    "name": "VIP PASS",
    "price": 1000.0,
    "was": 8550.0,
    "desc": "A $1,000 yearly membership that includes unlimited high-pressure tanning, UV tanning, Mystic tanning, red light therapy, and infrared sauna sessions , plus one 60-minute massage, one F+R Candle, 20% off tanning lotion, a birthday shout out on our Instagram and a pink lanyard with your photo! So fetch! A truly unbeatable deal! Valid for a one calendar year, buy now, start whenever. Example February 1, 2025-February 1, 2026.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p81_i1_w900.jpeg?width=640",
    "url": "https://shop.thepaintedladynapavalley.com/store/p81/VIP_PASS.html"
  },
  {
    "id": 82,
    "group": "Spray tans",
    "name": "Buy 5 Mystic Tans, Get 5 Free",
    "price": 140.0,
    "was": 280.0,
    "desc": "Mystic Tan is a self-tanning system that offers multiple bronzers with different undertones to create a custom natural glow for individual skin tones. It uses a patented spray-on process to apply tanning mist to the entire body in seconds, providing an even sunless tan",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p82_i1_w1512.jpeg?width=640",
    "url": "https://shop.thepaintedladynapavalley.com/store/p82/Buy_5_Mystic_Tans%2C_Get_5_Free.html"
  },
  {
    "id": 69,
    "group": "Spray tans",
    "name": "3 Airbrush Tans with Finishing Powder",
    "price": 120.0,
    "was": 180.0,
    "desc": "No more sticky spray tans! After your Lavish Spray tan, your tanning goddess applies a luxurious finishing powder. This powder eliminates that post spray tan sticky feeling on your entire body. It also protects the bronzer as it develops and leaves a beautiful light shimmer with a clean fresh amazing scent. Clothing and sheets are protected from bronzer.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p69_i1_w640.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p69/3_Airbrush_Tans_with_Finishing_Powder.html"
  },
  {
    "id": 68,
    "group": "Spray tans",
    "name": "3 Airbrush EXPRESS with Finishing Powder",
    "price": 170.0,
    "was": 240.0,
    "desc": "No more sticky spray tans! After your Lavish Spray tan, your tanning goddess applies a luxurious finishing powder. This powder eliminates that post spray tan sticky feeling on your entire body. It also protects the bronzer as it develops and leaves a beautiful light shimmer with a clean fresh amazing scent. Clothing and sheets are protected from bronzer.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p68_i2_w640.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p68/3_Airbrush_EXPRESS_with_Finishing_Powder.html"
  },
  {
    "id": 66,
    "group": "Spray tans",
    "name": "Airbrush EXPRESS with Finishing Powder BOGO",
    "price": 90.0,
    "was": 180.0,
    "desc": "No more sticky spray tans! After your Lavish Spray tan, your tanning goddess applies a luxurious finishing powder. This powder eliminates that post spray tan sticky feeling on your entire body. It also protects the bronzer as it develops and leaves a beautiful light shimmer with a clean fresh amazing scent. Clothing and sheets are protected from bronzer.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p66_i2_w640.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p66/Airbrush_EXPRESS_with_Finishing_Powder_BOGO.html"
  },
  {
    "id": 65,
    "group": "Spray tans",
    "name": "Airbrush Tan with Finishing Powder BOGO",
    "price": 70.0,
    "was": 140.0,
    "desc": "No more sticky spray tans! After your Lavish Spray tan, your tanning goddess applies a luxurious finishing powder. This powder eliminates that post spray tan sticky feeling on your entire body. It also protects the bronzer as it develops and leaves a beautiful light shimmer with a clean fresh amazing scent. Clothing and sheets are protected from bronzer.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p65_i1_w640.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p65/Airbrush_Tan_with_Finishing_Powder_BOGO.html"
  },
  {
    "id": 42,
    "group": "Spray tans",
    "name": "Buy 1 Mystic Tan, Get One Free",
    "price": 40.0,
    "was": 80.0,
    "desc": "2 gorgeous cocoa bronze MyMyst Mystic Spray Tans at an extreme discount! Pick any of these heavenly hues: Luminous Light, Magical Medium, or Dazzling Dark. Use them whenever you like, once you buy, theses Mystics never expire! Limit 6 packages per person.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p42_i5_w345.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p42/Buy_1_Mystic_Tan%2C_Get_One_Free.html"
  },
  {
    "id": 40,
    "group": "Spray tans",
    "name": "Buy 1 Lavish Airbrush Tan, Get One Free",
    "price": 60.0,
    "was": 120.0,
    "desc": "Lavish Tan created a patent pending, brown-sugar based solution derived from apples. The brown sugar base ensures golden brown color eliminating all possibilities of an orange tone. Most all other solutions on the market contain beat or carrot fermented extracts, which is where the orange tones and unpleasant scent stem from. We guarantee the highest quality, golden-brown results. Limit 6 packages per person. Buy now, and use these tans whenever you'd like!",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p40_i1_w640.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p40/Buy_1_Lavish_Airbrush_Tan%2C_Get_One_Free.html"
  },
  {
    "id": 39,
    "group": "Spray tans",
    "name": "Buy One Lavish EXPRESS Airbrush Tan, Get One Free",
    "price": 80.0,
    "was": 160.0,
    "desc": "​ EXPRESS solution gives you the option to shower in as little as 2-hours! Lavish Tan EXPRESS solution processes faster on the skin, allowing you to shower within only a few hours after application. Allow 2-hours for light shade, 3-hours for for medium-light shade, and 4-hours for a medium shade. Once you purchase, these tans never expire. Limit 6 Lavish Express Sessions per person.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p39_i2_w373.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p39/Buy_One_Lavish_EXPRESS_Airbrush_Tan%2C_Get_One_Free.html"
  },
  {
    "id": 26,
    "group": "Spray tans",
    "name": "3 Lavish EXPRESS Airbrush Spray Tans",
    "price": 150.0,
    "was": 240.0,
    "desc": "​ EXPRESS solution gives you the option to shower in as little as 2-hours! Lavish Tan EXPRESS solution processes faster on the skin, allowing you to shower within only a few hours after application. Allow 2-hours for light shade, 3-hours for for medium-light shade, and 4-hours for a medium shade. Once you purchase, these tans never expire. Limit 3 packages per person.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p26_i2_w373.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p26/3_Lavish_EXPRESS_Airbrush_Spray_Tans.html"
  },
  {
    "id": 24,
    "group": "Spray tans",
    "name": "$90 for 3 Lavish Airbrush Tans",
    "price": 90.0,
    "was": 150.0,
    "desc": "Lavish Tan created a patent pending, brown-sugar based solution derived from apples. The brown sugar base ensures golden brown color eliminating all possibilities of an orange tone. Most all other solutions on the market contain beat or carrot fermented extracts, which is where the orange tones and unpleasant scent stem from. We guarantee the highest quality, golden-brown results. Limit 6 packages per person. Buy now, and use these tans whenever you'd like!",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p24_i1_w640.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p24/%2490_for_3_Lavish_Airbrush_Tans.html"
  },
  {
    "id": 13,
    "group": "Spray tans",
    "name": "$100 for 10 MyMyst Mystic Tans",
    "price": 100.0,
    "was": 230.0,
    "desc": "10 gorgeous cocoa bronze MyMyst Mystic Spray Tans at an extreme discount! Pick any of these heavenly hues: Luminous Light, Magical Medium, or Dazzling Dark. Use them whenever you like, once you buy, theses Mystics never expire! Limit 6 packages per person.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p13_i5_w345.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p13/%24100_for_10_MyMyst_Mystic_Tans.html"
  },
  {
    "id": 67,
    "group": "UV tanning",
    "name": "Buy 1 High Pressure Tanning Session, Get on Free",
    "price": 49.5,
    "was": 99.0,
    "desc": "With the Matrix or Solarix X2 Tanning Bed, you will see the color difference immediately! While conventional tanning beds require 3 to 8 visits to establish a base tan, the High Pressure Tanning systems only requires 2 to 5 sessions. 10% Tanning Tax Included in Price. Limit 6 Packages per client.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p67_i3_w1200.jpeg?width=640",
    "url": "https://shop.thepaintedladynapavalley.com/store/p67/Buy_1_High_Pressure_Tanning_Session%2C_Get_on_Free.html"
  },
  {
    "id": 63,
    "group": "UV tanning",
    "name": "Buy 1 Month of High Pressure Tanning, Get 1 Month Free",
    "price": 165.0,
    "was": 330.0,
    "desc": "With the Matrix or Solarix X2 Tanning Bed, you will see the color difference immediately! While conventional tanning beds require 3 to 8 visits to establish a base tan, the High Pressure Tanning systems only requires 2 to 5 sessions. 10% Tanning Tax Included in Price. Limit 6 Packages per client.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p63_i2_w1200.jpeg?width=640",
    "url": "https://shop.thepaintedladynapavalley.com/store/p63/Buy_1_Month_of_High_Pressure_Tanning%2C_Get_1_Month_Free.html"
  },
  {
    "id": 58,
    "group": "UV tanning",
    "name": "Buy 5 High Pressure Tanning Sessions, Get 5 Free",
    "price": 148.5,
    "was": 297.0,
    "desc": "With the Matrix or Solarix X2 Tanning Bed, you will see the color difference immediately! While conventional tanning beds require 3 to 8 visits to establish a base tan, the High Pressure Tanning systems only requires 2 to 5 sessions. 10% Tanning Tax Included in Price. Limit 6 Packages per client . 10% Tanning Tax Included. Limit 10 Packages Per Customer.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p58_i1_w494.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p58/Buy_5__High_Pressure_Tanning_Sessions%2C_Get_5_Free.html"
  },
  {
    "id": 57,
    "group": "UV tanning",
    "name": "$220 for 10 High Pressure UV Sessions",
    "price": 220.0,
    "was": 275.0,
    "desc": "With the Solarix X2 and Matrix High Pressure Tanning Beds, you will see the color difference immediately! While conventional tanning beds require 3 to 8 visits to establish a base tan, the Solarix X2 system only requires 2 to 5 sessions. 10% Tanning Tax Included in Price. Limit 6 Packages per client.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p57_i1_w369.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p57/%24220_for_10_High_Pressure_UV_Sessions.html"
  },
  {
    "id": 56,
    "group": "UV tanning",
    "name": "$275 for 90 Days Unlimited High Pressure + All Other UV Beds",
    "price": 275.0,
    "was": 330.0,
    "desc": "Luxuriate in any of our four fierce tanning beds including the NEW SOLARIX. Buy now, but your 90 Days can start whenever you like! Cannot be combined with any other offer. Once you buy, this offer never expires, but the savings do! Limit 6 packages per person. Price includes 10% Tanning Tax. 90 Consecutive Days.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p56_i1_w494.png",
    "url": "https://shop.thepaintedladynapavalley.com/store/p56/%24275_for_90_Days_Unlimited_High_Pressure___All_Other_UV_Beds.html"
  },
  {
    "id": 51,
    "group": "UV tanning",
    "name": "$99 Buy 1 Month of Unlimited UV Tanning, Get 1 Month Free",
    "price": 99.0,
    "was": 198.0,
    "desc": "Two months for the price of one! Buy now, and start your two months whenever you'd like. Use any of our 3 (soon to be 4!) dazzling tanning beds. 10% Tanning Tax included in price.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p51_i1_w640.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p51/%2499_Buy_1_Month_of_Unlimited_UV_Tanning%2C_Get_1_Month_Free.html"
  },
  {
    "id": 44,
    "group": "UV tanning",
    "name": "90 Days of Standard Unlimited UV Tanning for $99",
    "price": 99.0,
    "was": 198.0,
    "desc": "Luxuriate in any of our three standard tanning beds. Buy now, but your 90 Days can start whenever you like! Cannot be combined with any other offer. Once you buy, this offer never expires, but the savings do! Limit 6 packages per person. Price includes 10% Tanning Tax",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p44_i2_w640.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p44/90_Days_of_Standard_Unlimited_UV_Tanning_for_%2499.html"
  },
  {
    "id": 38,
    "group": "UV tanning",
    "name": "Buy 5 UV Sessions, Get 5 Free",
    "price": 66.0,
    "was": 132.0,
    "desc": "Can't make it to The Painted Lady very often? Then purchasing sessions is the right move for you. Buy 5 UV sessions for $55 ($50 + tax) and receive 5 sessions free Limit 6 packages per person.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p38_i3_w600.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p38/10-UV-Sessions.html"
  },
  {
    "id": 33,
    "group": "UV tanning",
    "name": "$77 FOR 10 UV SESSIONS (10% TANNING TAX INCLUDED)",
    "price": 77.0,
    "was": 99.0,
    "desc": "Can't make it to The Painted Lady very often? Then purchasing sessions is the right move for you. Enjoy 10 UV tanning sessions (a $99 value) for only $77 in any of our standard tanning beds! Once you purchase, the tans never expire. Ever! 10% Tanning Tax Included. Limit 6 packages per person.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p33_i2_w494.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p33/10-UV-Sessions.html"
  },
  {
    "id": 86,
    "group": "Wellness",
    "name": "Buy One Glass Skin Facial, Get One Half Off",
    "price": 283.5,
    "was": 378.0,
    "desc": "Experience the ultimate in hydration and radiance with this luxurious facial using premium Korean skincare products. Designed to deeply cleanse, exfoliate, and nourish, this treatment smooths texture, plumps the skin, and leaves your complexion with a luminous, glass-like glow. Perfect for achieving that dewy, flawless look while strengthening and revitalizing your skin. 90 minutes Best for: Dull, Textured, Dehydrated skin",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p86_i1_w870.jpeg?width=640",
    "url": "https://shop.thepaintedladynapavalley.com/store/p86/Buy_One_Glass_Skin_Facial%2C_Get_One_Half_Off.html"
  },
  {
    "id": 83,
    "group": "Wellness",
    "name": "BOGO 60-Minute Massages with Logan (Thursdays, Fridays and Sundays only)",
    "price": 150.0,
    "was": 200.0,
    "desc": "Buy one, get one half off. The Painted Lady's masterful massage therapists integrate techniques of Swedish massage, acupressure, and deep tissue, providing an individualized experience to ease muscle pain and tension, and promote feelings of deep relaxation and well-being. Limit 6 Massages per person. Buy now, but these massages never expire. NOT VALID WITH JULIE. THURSDAY, FRIDAY AND SUNDAYS ONLY.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p83_i3_w562.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p83/BOGO_60-Minute_Massages_with_Logan_%28Thursdays%2C_Fridays_and_Sundays_only%29.html"
  },
  {
    "id": 80,
    "group": "Wellness",
    "name": "Buy 1 60 Minute Massage, Get One Half Off",
    "price": 150.0,
    "was": 200.0,
    "desc": "The Painted Lady's masterful massage therapist integrate techniques of Swedish massage, acupressure, and deep tissue, providing an individualized experience to ease muscle pain and tension, and promote feelings of deep relaxation and well-being. Massage is redeemable on Fridays & Sundays only. Not valid with Julie.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p80_i3_w1500.jpeg?width=640",
    "url": "https://shop.thepaintedladynapavalley.com/store/p80/Buy_1_60_Minute_Massage%2C_Get_One_Half_Off.html"
  },
  {
    "id": 79,
    "group": "Wellness",
    "name": "3 60 Minute Massages for $200",
    "price": 200.0,
    "was": 300.0,
    "desc": "Pamper Yourself with a Black Friday Exclusive! Enjoy 3 relaxing 60-minute massages for just $200 (regularly $300). Available Fridays and Sundays only – NOT redeemable with Julie . Book yours soon!",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p79_i1_w221.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p79/3_60_Minute_Massages_for_%24200.html"
  },
  {
    "id": 75,
    "group": "Wellness",
    "name": "10 Infrared Sauna Sessions",
    "price": 100.0,
    "was": 230.0,
    "desc": "Sunlight is a combination of visible light and invisible light. The seven colors of the rainbow are visible lights, and infrared rays and ultraviolet rays are invisible lights. Infrared rays are one of the sun’s rays. Infrared rays are the healthiest, penetrate into your skin deeply and they dissolve harmful substances accumulated in your body. The infrared rays vitalize your cells and metabolism. NEW: Double the healing radiance with our infrared sauna's new RED LIGHT THERAPY heater.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p75_i1_w532.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p75/10_Infrared_Sauna_Sessions.html"
  },
  {
    "id": 61,
    "group": "Wellness",
    "name": "Buy One Month of Unlimited Sauna Use, get one month free!",
    "price": 200.0,
    "was": 400.0,
    "desc": "Sunlight is a combination of visible light and invisible light. The seven colors of the rainbow are visible lights, and infrared rays and ultraviolet rays are invisible lights. Infrared rays are one of the sun’s rays. Infrared rays are the healthiest, penetrate into your skin deeply and they dissolve harmful substances accumulated in your body. The infrared rays vitalize your cells and metabolism.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p61_i1_w532.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p61/Buy_One_Month_of_Unlimited_Sauna_Use%2C_get_one_month_free%21.html"
  },
  {
    "id": 43,
    "group": "Wellness",
    "name": "Buy one 90 Minute Massage, Get One Free (Fridays & Sundays Only)",
    "price": 130.0,
    "was": 260.0,
    "desc": "The Painted Lady's masterful massage therapists integrate techniques of Swedish massage, acupressure, and deep tissue, providing an individualized experience to ease muscle pain and tension, and promote feelings of deep relaxation and well-being. Limit 6 Massages per person. Buy now, but these massages never expire. NOT VALID WITH JULIE. FRIDAY AND SUNDAYS ONLY.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p43_i2_w275.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p43/Buy_one_90_Minute_Massage%2C_Get_One_Free_%28Fridays_%26_Sundays_Only%29.html"
  },
  {
    "id": 41,
    "group": "Wellness",
    "name": "Buy one month of Red Light Therapy, Get One Month Free",
    "price": 80.0,
    "was": 160.0,
    "desc": "The Beauty Angel uses light in special ranges of effectiveness to rejuvenate the skin naturally. Small wrinkles are reduced and the skin becomes visibly tauter and smoother. Buy now, but the 60 days don't begin until your first visit. Limit 6 packages per person.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p41_i5_w450.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p41/Buy_one_month_of_Red_Light_Therapy%2C_Get_One_Month_Free.html"
  },
  {
    "id": 37,
    "group": "Wellness",
    "name": "Buy 1 60 Minute Massage, Get One Free (Fridays & Sundays Only)",
    "price": 100.0,
    "was": 200.0,
    "desc": "The Painted Lady's masterful massage therapist integrate techniques of Swedish massage, acupressure, and deep tissue, providing an individualized experience to ease muscle pain and tension, and promote feelings of deep relaxation and well-being. Massage is redeemable on Fridays & Sundays only. Not valid with Julie.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p37_i2_w865.jpeg?width=640",
    "url": "https://shop.thepaintedladynapavalley.com/store/p37/Buy_1_60_Minute_Massage%2C_Get_One_Free_%28Fridays_%26_Sundays_Only%29.html"
  },
  {
    "id": 15,
    "group": "Wellness",
    "name": "$90 FOR 90 DAYS OF RED LIGHT THERAPY",
    "price": 90.0,
    "was": 180.0,
    "desc": "The Beauty Angel uses light in special ranges of effectiveness to rejuvenate the skin naturally. Small wrinkles are reduced and the skin becomes visibly tauter and smoother. Buy now, but the 90 days don't begin until your first visit. Limit 6 packages per person.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p15_i5_w450.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p15/%2490_FOR_90_DAYS_OF_RED_LIGHT_THERAPY.html"
  },
  {
    "id": 78,
    "group": "Take-home",
    "name": "Buy one F+R Candle, get a F+R Lip Balm Free",
    "price": 21.8,
    "was": 27.0,
    "desc": "",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p78_i1_w1280.jpeg?width=640",
    "url": "https://shop.thepaintedladynapavalley.com/store/p78/Buy_one_F_R_Candle%2C_get_a_F_R_Lip_Balm_Free.html"
  },
  {
    "id": 45,
    "group": "Take-home",
    "name": "Buy any Packet of Tanning Lotion, Get any Additional Packet Free",
    "price": 5.4,
    "was": 10.8,
    "desc": "​ Make your skin the object of everyone’s affection with any two packets of The Painted Lady's tanning lotions. Powerful dark tanning technology blended with Skin Firming Conditioners and Silky Smooth Silicones take your tan to new heights of dark desirable color. Go ahead, show your skin some love. Sales Tax included.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p45_i8_w400.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p45/Buy_any_Packet_of_Tanning_Lotion%2C_Get_any_Additional_Packet_Free.html"
  },
  {
    "id": 28,
    "group": "Take-home",
    "name": "Any Bottle of Tanning Lotion for $40 + tax",
    "price": 43.6,
    "was": 76.3,
    "desc": "Make your skin the object of everyone’s affection with this any of The Painted Lady's tanning lotions. Powerful dark tanning technology blended with Skin Firming Conditioners and Silky Smooth Silicones take your tan to new heights of dark desirable color. Go ahead, show your skin some love.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p28_i7_w415.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p28/Any_Bottle_of_Tanning_Lotion_for_%2440___tax.html"
  },
  {
    "id": 21,
    "group": "Take-home",
    "name": "Buy any Bottle of Tanning Lotion, Get any Additional Bottle Free",
    "price": 109.0,
    "was": 218.0,
    "desc": "​ Make your skin the object of everyone’s affection with any two bottles of The Painted Lady's tanning lotions. Powerful dark tanning technology blended with Skin Firming Conditioners and Silky Smooth Silicones take your tan to new heights of dark desirable color. Go ahead, show your skin some love.",
    "img": "https://shop.thepaintedladynapavalley.com/uploads/2/3/3/9/23398226/s114532324311945421_p21_i7_w400.jpeg",
    "url": "https://shop.thepaintedladynapavalley.com/store/p21/Buy_any_Bottle_of_Tanning_Lotion%2C_Get_any_Additional_Bottle_Free.html"
  }
]
};
