#!/usr/bin/env python3
"""Write redirect stubs for the old Weebly page URLs (GitHub Pages can't send real 301s).

Run from the repo root:  python3 _build/build_redirects.py

Each old address (e.g. /uv.html) gets a tiny page with an instant meta refresh + canonical link to its
new home. Google treats an instant meta refresh as a permanent redirect, so the old pages' search
history passes to the new ones. (404.html keeps a script fallback for anything not listed here,
including /store/* product links, which go to the same path on the shop. subdomain.)
Checks that every target page exists and every #anchor is present before writing.
"""
import html, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = "https://www.thepaintedladynapavalley.com"
SHOP = "https://shop.thepaintedladynapavalley.com"

# old path → new target (site path with optional #anchor, or a full URL)
MOVED = {
    "uv.html": "tanning.html#beds", "soltron-wildcat.html": "tanning.html#beds",
    "ergoline-essence-48.html": "tanning.html#beds", "dr-muller-elixir.html": "tanning.html#beds",
    "solarix-2.html": "tanning.html#beds", "matrix.html": "tanning.html#beds",
    "spray.html": "tanning.html#airbrush", "airbrush-spray-tan.html": "tanning.html#airbrush",
    "mystic-spray-tan.html": "tanning.html#mystic",
    "frequently-asked-questions.html": "guide.html#faq", "dha.html": "guide.html#dha",
    "red-light.html": "wellness.html#red-light", "the-beauty-angel.html": "wellness.html#red-light",
    "sauna.html": "wellness.html#sauna", "skin-care-by-court.html": "wellness.html#skin",
    "massage.html": "wellness.html#massage", "safe-haven-massage-with-logan.html": "wellness.html#massage",
    "goddess-healing-hands.html": "wellness.html#massage",
    "prices.html": "menu.html", "contact.html": "visit.html",
    "bios.html": "team.html", "bios1.html": "team.html",
    "alli.html": "team.html#alli", "alec.html": "team.html#alec", "sharon.html": "team.html#sharon",
    "courtney.html": "team.html#courtney", "logan.html": "team.html#logan", "toni.html": "team.html#toni",
    "summerween.html": f"{SHOP}/summerween.html",   # seasonal sale page: lives on in the Weebly store
}
# Anchors rendered by JavaScript (team profiles) don't appear in the HTML; list them here.
JS_ANCHORS = {"team.html": {"alli", "alec", "sharon", "courtney", "logan", "toni"}}

STUB = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{title} · The Painted Lady Tanning &amp; Spa</title>
  <!-- Redirect stub for an old Weebly address (generated by _build/build_redirects.py; don't edit by hand) -->
  <link rel="canonical" href="{canonical}">
  <meta http-equiv="refresh" content="0; url={href}">
  <script>location.replace({js});</script>
</head>
<body>
  <p>This page has moved: <a href="{href}">{title}</a>.</p>
</body>
</html>
"""

TITLES = {"tanning.html": "The Tan", "wellness.html": "Wellness", "menu.html": "Price List", "team.html": "The Cast",
          "guide.html": "The Glow Guide", "visit.html": "Visit"}


def main():
    errors = []
    for old, target in MOVED.items():
        if (ROOT / old).exists() and "Redirect stub" not in (ROOT / old).read_text():
            errors.append(f"{old}: a real page already uses this name")
        if target.startswith("http"):
            continue
        page, _, anchor = target.partition("#")
        f = ROOT / page
        if not f.exists():
            errors.append(f"{old} -> {target}: {page} doesn't exist")
        elif anchor and anchor not in JS_ANCHORS.get(page, set()) and not re.search(rf'id="{re.escape(anchor)}"', f.read_text()):
            errors.append(f"{old} -> {target}: no id=\"{anchor}\" in {page}")
    if errors:
        sys.exit("Not writing redirects:\n  " + "\n  ".join(errors))

    for old, target in MOVED.items():
        external = target.startswith("http")
        href = target if external else "/" + target
        canonical = target.split("#")[0] if external else f"{SITE}/{target.split('#')[0]}"
        title = "Summerween sale" if old == "summerween.html" else TITLES.get(target.split("#")[0], "The Painted Lady")
        (ROOT / old).write_text(STUB.format(title=html.escape(title), canonical=canonical, href=html.escape(href),
                                            js=repr(href).replace("'", '"')))
    print(f"Wrote {len(MOVED)} redirect stubs.")


if __name__ == "__main__":
    main()
